name: Fetch GitHub Stats

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Fetch GitHub Stats
        run: |
          curl -H "Authorization: token ${{ secrets.GH_README_STATS_PAT }}" \
          -o stats.svg "https://github-readme-stats.vercel.app/api/top-langs/?username=${{ github.repository_owner }}&hide=css,html&show_icons=true&theme=radical&count_private=true&include_all_commits=true"
        
      - name: Commit stats
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add stats.svg
          git commit -m "Update stats"
          git push
