name: Fetch GitHub Stats

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Fetch Stats
      env:
        GH_TOKEN: ${{ secrets.GH_README_STATS_PAT }}
      run: |
        curl -H "Authorization: token $GH_TOKEN" -f https://github-readme-stats.vercel.app/api/top-langs/?username=Elevatorisbest&count_private=true > stats.svg
    - name: Commit files
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add stats.svg
        git commit -m "Updated stats" || exit 0
        git push
